<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SkillXpAnnouncer</AssemblyName>
    <RootNamespace>SkillXpAnnouncer</RootNamespace>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>7.3</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\Bin\Win64_Shipping_Client\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>E:\SteamLibrary\steamapps\common\Mount &amp; Blade II Bannerlord\Modules\Bannerlord.Harmony\bin\Win64_Shipping_Client\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MCMv5">
      <HintPath>E:\SteamLibrary\steamapps\common\Mount &amp; Blade II Bannerlord\Modules\Bannerlord.MBOptionScreen\bin\Win64_Shipping_Client\MCMv5.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.CampaignSystem">
      <HintPath>E:\SteamLibrary\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.CampaignSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.Core">
      <HintPath>E:\SteamLibrary\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.DotNet">
      <HintPath>E:\SteamLibrary\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.DotNet.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.Engine">
      <HintPath>E:\SteamLibrary\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Engine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.Engine.GauntletUI">
      <HintPath>E:\SteamLibrary\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Engine.GauntletUI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.GauntletUI">
      <HintPath>E:\SteamLibrary\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.GauntletUI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.GauntletUI.Data">
      <HintPath>E:\SteamLibrary\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.GauntletUI.Data.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.InputSystem">
      <HintPath>E:\SteamLibrary\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.InputSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.Library">
      <HintPath>E:\SteamLibrary\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Library.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.Localization">
      <HintPath>E:\SteamLibrary\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Localization.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.MountAndBlade">
      <HintPath>E:\SteamLibrary\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.MountAndBlade.View">
      <HintPath>E:\SteamLibrary\steamapps\common\Mount &amp; Blade II Bannerlord\Modules\Native\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.View.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.ObjectSystem">
      <HintPath>E:\SteamLibrary\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.ObjectSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.ScreenSystem">
      <HintPath>E:\SteamLibrary\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.ScreenSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.TwoDimension">
      <HintPath>E:\SteamLibrary\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.TwoDimension.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
